### ISSUE TITLE
Line 69 of PriorityBooster.cpp doesn't have a name for one of its parameters

### ISSUE THREAD

**Issue by tekwizz123** [zodiacon/windowskernelprogrammingbook#1]
The code for this line is as follows:

`NTSTATUS PriorityBoosterDeviceControl(PDEVICE_OBJECT, PIRP Irp) {`

Shouldn't there be a name for PDEVICE_OBJECT parameter as well as an associated UNREFERENCED_PARAMETER() line? Or am I missing something here?

**Comment by zodiacon** [comment]
C++ allows omitting parameter names, so using a name and then UNREFERENCE_PARAMETER (which really does reference the parameter) is equivalent. In C you must provide a name for all parameters.

**Comment by tekwizz123** [comment]
Thanks I am used to the C programming language standards so I didn't realize that this was the case. Appreciate the explanation! Will close the issue now as this has been resolved.
