### ISSUE TITLE
processprotect in chap9 delete via taskmanager kills/terminates protected process

### ISSUE THREAD

**Issue by manurautela** [zodiacon/windowskernelprogrammingbook#2]
Hi Pavel,

https://github.com/zodiacon/windowskernelprogrammingbook/tree/master/chapter09/ProcessProtect

Following the instructions of the book to terminate process via taskmanager, when it's being protected still goes ahead and terminates the process.

![image](https://user-images.githubusercontent.com/1333906/63045115-4d01c900-beed-11e9-8929-d1c565ddb878.png)

To validate otherwise,  i  created a sample app which tried to open the proecess with PROCESS_TERMINATE access and then terminate the process. In this case however trying to terminate the process  with the handle gives back a handle that doesn't terminate process.
![image](https://user-images.githubusercontent.com/1333906/63045281-a8cc5200-beed-11e9-8137-820e88cf873e.png)

please have a look.

**Comment by zodiacon** [comment]
If you terminate using Task manager Processes tab, Task Manager does not call TerminateProcess, but instead calls SendMessage(hWnd, WM_CLOSE, 0, 0) to close the main window. This makes the process exit normally (ExitProcess).
If you to terminate from the Details tab, it should fail.

**Comment by manurautela** [comment]
Thanks for insight.

But the chapter mentions and shares a screenshot where we try to terminate the process via taskmanager and an access denied prompt is shown.

![image](https://user-images.githubusercontent.com/1333906/63048120-7aea0c00-bef3-11e9-9954-5318bbab4094.png)

**Comment by zodiacon** [comment]
Yes, my bad, there is End Task in the Details tab, too.
I need to make that clear in the text.
Thanks

**Comment by manurautela** [comment]
Thanks, I just double checked via Details tab. Now it's clear and working (meaning getting an access denied message popup ) :)
