### ISSUE TITLE
Init value maybe it will be better

### ISSUE THREAD

**Issue by skrandy** [zodiacon/windowskernelprogrammingbook#3]
https://github.com/zodiacon/windowskernelprogrammingbook/blob/master/chapter09/ProcessProtect/ProcessProtect.h

i think,if we add a line code in Globals::Init() will be better:
`
memset(Pids,0x0,MaxPids);
`
so this func will be:

`
	void Init() {
		Lock.Init();
	        memset(Pids,0x0,MaxPids);
         }
`

Just an idea of mine, maybe I'm wrong.
thank you for reading

**Comment by zodiacon** [comment]
Not needed, since global objects are always zero-initialized,

**Comment by skrandy** [comment]
such as the follow codes:
`class A
{
public:
    char temp[0x100];
};


int main()
{
    A a;
    printf(a.temp);
    system("pause");
    return 0;
}`

the a.temp array always have some unpredictable values

**Comment by zodiacon** [comment]
Yes, this is a local variable.
Global variables are always zeroed.

**Comment by skrandy** [comment]
Sorry, it was my problem, you are right.
just like as follow code:
`#include<iostream>

class A
{
public:
    char temp[0x100];
};
A a;

int main()
{
    printf(a.temp);
    system("pause");
    return 0;
}`
the a.temp array is inited as zero
