### ISSUE TITLE
I get a BSOD when the example "zero" in chap7 running

### ISSUE THREAD

**Issue by ehnap** [zodiacon/windowskernelprogrammingbook#4]
Because line 85 in Zero.cpp: 
`auto buffer = MmGetSystemAddressForMdlSafe(Irp->MdlAddress, NormalPagePriority);`
Irp->MdlAddress is null.

I search some solutions on the internet. And i found that user data is in Irp->UserBuffer.
I guess the reason is: 
**ZeroTest.exe didn't use DeviceIoControl but ReadFile. So the Method of IoControlCode isn't METHOD_IN_DIRECT or METHOD_OUT_DIRECT.**

I don't know the relationship between ReadFile and DeviceIoControl. So I'm not sure if I'm right.
And I also have a question: Can I set METHOD_OUT_DIRECT to kernel when I use ReadFile in user mode. Or I can only use DeviceIoControl when I need METHOD_OUT_DIRECT ?

**Comment by ehnap** [comment]
Sorry it's my fault. 
My code is:
`DriverObject->Flags |= DO_DIRECT_IO;`
the code should be:
`DeviceObject->Flags |= DO_DIRECT_IO;`

**Comment by zodiacon** [comment]
It's a common error :)
