### ISSUE TITLE
DelProtect3(char10): When saving files to the protected directory, something strange happens

### ISSUE THREAD

**Issue by adream100** [zodiacon/windowskernelprogrammingbook#6]
I run notepad.exe, input something, save it to C:\Test, the protected directory( I use cmd:  DelProtect3Config add C:\Test),  a windows warning messagebox popped up, as you can see below:
![image](https://github.com/zodiacon/windowskernelprogrammingbook/assets/153361306/3ca72e7d-b81d-4b5e-8f0f-f1f9fac458e1)
What is the reason? Can it be improved?

**Comment by adream100** [comment]
I got it. notepad's "save" or" save as" function will create a temporary file with the same name and then deleting it  before creating a new file. Probably to prevent a double name.

**Comment by zodiacon** [comment]
Thanks for looking into it!
